export const mockData = [
  {
    id: 1,
    lastName: 'Omar',
    firstName: 'ashraf',
    userName: 'omar.ashraf1',
    age: 35,
    emailAddress: 'fdsfdsdfs@gmail.com',
    status: 'Active',
    date: '10/10/2022',
  },
  {
    id: 2,
    userName: 'ahemedsalem12',
    emailAddress: 'dasdsa@gmail.com',
    lastName: 'salem',
    firstName: 'ahmed',
    age: 42,
    status: 'Inactive',
    date: '10/15/2022',
  },
  {
    id: 3,
    userName: 'john.wick.07',
    emailAddress: 'john@gmail.com',
    lastName: 'wick',
    firstName: 'John',
    age: 45,
    status: 'Locked',
    date: '10/20/2022',
  },
  {
    id: 4,
    userName: 'Stark',
    emailAddress: 'stark122@gmail.com',
    lastName: 'Snow',
    firstName: 'stark',
    age: 16,
    status: 'Active',
    date: '10/25/2022',
  },
  {
    id: 5,
    userName: 'Targaryen',
    lastName: 'Good',
    firstName: 'Targaryen',
    emailAddress: 'Targaryen44@gmail.com',
    age: 41,
    status: 'Active',
    date: '11/15/2022',
  },
  {
    id: 6,
    userName: 'Melisandre',
    lastName: 'Snow',
    firstName: 'Jon',
    emailAddress: 'Melisandre@gmail.com',
    age: 150,
    status: 'Inactive',
    date: '12/15/2022',
  },
  {
    id: 7,
    userName: 'Clifford',
    lastName: 'yehia',
    firstName: 'Clifford',
    emailAddress: 'Cliffordd885@gmail.com',
    age: 44,
    status: 'Locked',
    date: '12/11/2022',
  },
  {
    id: 8,
    userName: 'Frances',
    lastName: 'Roxie',
    firstName: 'Frances',
    emailAddress: 'dsasad@gmail.com',
    age: 36,
    status: 'Active',
    date: '12/17/2022',
  },
  {
    id: 9,
    userName: 'Roxie',
    lastName: 'Snow',
    firstName: 'Roxie',
    emailAddress: 'wdqwfw@gmail.com',
    age: 65,
    status: 'Inactive',
    date: '11/18/2022',
  },
];
